export const HOME = 'HOME';
export const FETCH_RECITERS = 'FETCH_RECITERS';
export const FETCH_RECITERS_FAIL = 'FETCH_RECITERS_FAIL';
// reciter
export const FETCH_RECITER = 'FETCH_RECITERS';
export const FETCH_RECITER_FAIL = 'FETCH_RECITERS';
// search
export const SEARCH = 'SEARCH';
export const SEARCH_CLEAR = 'SEARCH_CLEAR';

// chapter
export const FETCH_CHAPTERS = 'FETCH_CHAPTERS';
export const FETCH_CHAPTERS_FAIL = 'FETCH_CHAPTERS_FAIL';
export const SELECT_CHAPTER_TO_PLAY = 'SELECT_CHAPTER_TO_PLAY';

// Music player
export const AUDIO_PLAYER_PLAY_SURAH = 'AUDIO_PLAYER_PLAY_SURAH';
export const AUDIO_PLAYER_GO_FORWARD = 'AUDIO_PLAYER_GO_FORWARD';
export const AUDIO_PLAYER_GO_BACKWARD = 'AUDIO_PLAYER_GO_BACKWARD';
export const AUDIO_PLAYER_SET_SURAHS_LIST = 'AUDIO_PLAYER_SET_SURAHS_LIST';
export const AUDIO_PLAYER_SET_SELECTED_SURAH_INDEX = 'AUDIO_PLAYER_SET_SELECTED_SURAH_INDEX';
export const AUDIO_PLAYER_MINIMISE = 'AUDIO_PLAYER_MINIMISE';
export const UPDATE_IS_PLAYING = 'UPDATE_IS_PLAYING';
export const UPDATE_IS_BACKGROUND_PLAY = 'UPDATE_IS_BACKGROUND_PLAY';

// Files
export const GET_FILES = 'GET_FILES';
export const GET_FILES_FAIL = 'GET_FILES_FAIL';
