export const HOME = 'HOME';
export const FETCH_RECITERS = 'FETCH_RECITERS';
export const FETCH_RECITERS_FAIL = 'FETCH_RECITERS_FAIL';
// reciter
export const FETCH_RECITER = 'FETCH_RECITERS';
export const FETCH_RECITER_FAIL = 'FETCH_RECITERS';
// search
export const SEARCH = 'SEARCH';
export const SEARCH_CLEAR = 'SEARCH_CLEAR';

// chapter
export const FETCH_CHAPTERS = 'FETCH_CHAPTERS';
export const FETCH_CHAPTERS_FAIL = 'FETCH_CHAPTERS_FAIL';

// Music player
export const MUSIC_PLAYER_PLAY_SONG = 'MUSIC_PLAYER_PLAY_SONG';
export const MUSIC_PLAYER_GO_FORWARD = 'MUSIC_PLAYER_GO_FORWARD';
export const MUSIC_PLAYER_GO_BACKWARD = 'MUSIC_PLAYER_GO_BACKWARD';
export const MUSIC_PLAYER_SET_SONGS_LIST = 'MUSIC_PLAYER_SET_SONGS_LIST';
export const MUSIC_PLAYER_SET_SELECTED_SONG_INDEX = 'MUSIC_PLAYER_SET_SELECTED_SONG_INDEX';
export const MUSIC_PLAYER_SET_CURRENT_TIME = 'MUSIC_PLAYER_SET_CURRENT_TIME';